/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SWAlgo {
  public static readonly int MAX_NB_PLAYERS = SWAlgoPINVOKE.MAX_NB_PLAYERS_get();
  public static readonly int TILE_FIELD = SWAlgoPINVOKE.TILE_FIELD_get();
  public static readonly int TILE_MOUNTAIN = SWAlgoPINVOKE.TILE_MOUNTAIN_get();
  public static readonly int TILE_DESERT = SWAlgoPINVOKE.TILE_DESERT_get();
  public static readonly int TILE_FOREST = SWAlgoPINVOKE.TILE_FOREST_get();
  public static readonly int TILE_WATER = SWAlgoPINVOKE.TILE_WATER_get();
}
